language: node_js
node_js:
  - "6.0"
before_install:
before_script:
  - npm i
script:
  - npm run lint
  - npm run build
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8